---
- name: Install and configure keepalived as a solo load balancer
  hosts: all
  become: yes

  tasks:

    - name: '[RHEL] install keepalived'
      yum:
        name: keepalived
        state: latest
        update_cache: yes
        disable_gpg_check: yes
      when:
        - ansible_distribution_file_variety == 'RedHat'
      tags:
        - install

    - name: '[Debian] install keepalived'
      apt:
        name: keepalived
        state: latest
        update_cache: yes
      when:
        - ansible_distribution_file_variety == 'Debian'
      tags:
        - install

    - name: 'enable forwarding'
      sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        sysctl_set: yes

    - name: 'change sysctl.conf file-max'
      sysctl:
        name: fs.file-max
        value: '{{ limit }}'
        state: present
        sysctl_set: yes

    - name: 'change ulimit -n'
      lineinfile:
        path: /etc/security/limits.conf
        line: |
          *     soft nofile {{ limit }}
          *     hard nofile {{ limit }}

    - name: 'copy keepalived config master'
      template:
        src: keepalived-master.conf.j2
        dest: /etc/keepalived/keepalived.conf
      notify: restart-keepalived
      when: inventory_hostname == keep_master

    - name: 'copy keepalived config backup'
      template:
        src: keepalived-backup.conf.j2
        dest: /etc/keepalived/keepalived.conf
      notify: restart-keepalived
      when: inventory_hostname == keep_backup


  handlers:

    - name: restart-keepalived
      systemd:
        name: keepalived
        state: restarted
        enabled: yes
